### ISSUE TITLE
OpenPGP: `GET DATA` returns unwrapped constructed DO's 

### ISSUE THREAD

**Issue by stv0g** [f-secure-foundry/GoKey#6]
Page 22 of OpenPGP card spec 3.4.1 says:

> Constructed DOs (C, marked yellow) are returned including their tag and length

However GoKey returns them without a wrapping TLV header:

- https://github.com/usbarmory/GoKey/blob/7dff54c51e1ed7a454e60e5656a5edf55bc45396/internal/icc/data.go#L397
- https://github.com/usbarmory/GoKey/blob/7dff54c51e1ed7a454e60e5656a5edf55bc45396/internal/icc/data.go#L391
- https://github.com/usbarmory/GoKey/blob/7dff54c51e1ed7a454e60e5656a5edf55bc45396/internal/icc/data.go#L211

This issue has been found when testing GoKey against [openpgp-card-tools](https://crates.io/crates/openpgp-card-tools/0.9.5).

See:
- https://gitlab.com/openpgp-card/openpgp-card/-/issues/71
- https://gitlab.com/openpgp-card/virtual-cards/-/merge_requests/2

**Comment by abarisani** [comment]
This should now be fixed, please re-open of necessary. Thanks!
